version: 0.1
phases:
  install:
    commands:
      - npm install -g
      - npm install -g serverless --unsafe-perm
  build:
    commands:
      - serverless config credentials --provider aws --key AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY
      - serverless deploy -v --config serverless.yml