version: 0.1
phases:
  install:
    commands:
      - npm install -g
      - npm install -g serverless
  pre_build:
    commands:
      - zip -r api.zip
  build:
    commands:
      - serverless deploy -v