service: portfolioAPI

provider: 
  name: aws 
  runtime: nodejs14.x
  stage: dev 
  region: us-west-1 
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "*"
      Resource: "*"

functions: 
  app: 
    handler: app.handler 
    events: 
      - http: 
          path: / 
          method: ANY 
      - http: 
            path: /{proxy+} 
            method: ANY